### ISSUE TITLE
Universal

### ISSUE THREAD

**Issue by eivholt** [bitrave/azure-mobile-services-for-unity3d#4]
Hi, I'm facing some problems with the new version, I am hoping you can explain.
I get the whole project from git, open AzureMobileServicesUniversalPlugin in Unity. I import JsonDotNet. Now I get compiler error that RestSharp is missing. I can't find any RestSharp-plugin for Unity and I was under the impression this could be used out of the box, not requiring local build? I'm currently trying to compile solution AzureMobileServicesUniversalPlugin with RestSharp added with nuget but nuget is acting up with an error I am unfamiliar with: NuGet Package restore failed for project Miscellaneous Files: Value cannot be null or an empty string.
Parameter name: root.

**Comment by vaughanknight** [comment]
That would be because I didn't check it in.  My apologies.  I had the plugins directory excluded from source control, and it has a version of RestSharp that is more cross platform.  I'll check it in on Monday, as I'm away this weekend.  And yes - You don't have to build anything with the new version, it all just works nicely across platforms.

**Comment by eivholt** [comment]
Thank you for the clarification, I'll wait for the update and continue playing around with it!

**Comment by vaughanknight** [comment]
The issue was the DLL's were in the git ignore list.  They should be there now.

**Comment by eivholt** [comment]
I will have another go tonight, thanks!
